Use move instead of obsolete proc
Fixes this error when compiling the library:

   Compiling xdg v0.1.0 (file:///home/project/packontrack/rust-xdg)
src/xdg.rs:292:9: 292:13 error: obsolete syntax: `proc` expression
src/xdg.rs:292         proc()
                       ^~~~
note: use a `move ||` expression instead
error: aborting due to previous error
Could not compile `xdg`.